spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/customerdb
    username: admin
    password: password
  tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  profiles:
    active: spring.profiles.active
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        id:
          new_generator_mappings: false
        format_sql: true
  application:
    name: Customer-Management-System
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
#logging.level.org.springframework: DEBUG
server:
  port: 8081
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
management:
  security:
    enabled: false  
ribbon:
  https:
    client: 
      enabled: true
#logging:
  #level:
    #com.self.sprintboot.learning.employee: DEBUG
